name: 'Build Python Source and Wheel Distributions'
description: 'Build source distribution for any Python package and wheels for Python packages without extensions.'
branding:
  icon: package
  color: blue
inputs:
  test_extras:
    description: Any extras_requires modifier that should be used to install the package for testing
    required: false
    default: ''
    type: string
  test_command:
    description: The command to run to test the package (will be run in a temporary directory)
    required: false
    default: ''
    type: string
  pure_python_wheel:
    description: Whether to build a pure Python wheel in addition to the source distribution
    required: false
    default: false
    type: string
  python-version:
    description: The Python version to use for building and testing
    required: false
    default: '3.x'
    type: string
runs:
  using: "composite"
  steps:

  - uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}

  - name: Install python-build and twine
    shell: bash
    run: python -m pip install pip build twine --upgrade

  - name: Build source distribution
    shell: bash
    run: python -m build --sdist .

  - name: Test source distribution
    shell: bash
    run: |
      python -m venv test-sdist
      test-sdist/bin/activate
      which python
      python -m pip install --force-reinstall `find dist -name "*.tar.gz"`[${{ inputs.test_extras }}]
      cd ${{ runner.temp }}
      ${{ inputs.test_command }}
    if: ${{ inputs.test_command != '' && inputs.test_extras != '' }}

  - name: Test source distribution
    shell: bash
    run: |
      python -m venv test-sdist
      test-sdist/bin/activate
      which python
      python -m pip install --force-reinstall `find dist -name "*.tar.gz"`
      cd ${{ runner.temp }}
      ${{ inputs.test_command }}
    if: ${{ inputs.test_command != '' && inputs.test_extras == '' }}

  - name: Build pure Python wheel distribution
    shell: bash
    run: python -m build --wheel .
    if: ${{ inputs.pure_python_wheel == 'true' }}

  # TODO: check that the resulting wheel is indeed pure Python

  - name: Test pure Python wheel distribution
    shell: bash
    run: |
      python -m venv test-wheel
      test-wheel/bin/activate
      which python
      python -m pip install --force-reinstall `find dist -name "*.whl"`[${{ inputs.test_extras }}]
      cd ${{ runner.temp }}
      ${{ inputs.test_command }}
    if: ${{ inputs.pure_python_wheel == 'true' && inputs.test_command != '' && inputs.test_extras != '' }}

  - name: Test pure Python wheel distribution
    shell: bash
    run: |
      python -m venv test-wheel
      test-wheel/bin/activate
      which python
      python -m pip install --force-reinstall `find dist -name "*.whl"`
      cd ${{ runner.temp }}
      ${{ inputs.test_command }}
    if: ${{ inputs.pure_python_wheel == 'true' && inputs.test_command != '' && inputs.test_extras == '' }}
